apiVersion: v1
kind: Service
metadata:
  name: {{ include "open-webui.name" . }}
  labels:
    {{- include "open-webui.labels" . | nindent 4 }}
  {{- with .Values.webui.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "open-webui.selectorLabels" . | nindent 4 }}
{{- with .Values.webui.service }}
  type: {{ .type }}
  ports:
  - protocol: TCP
    name: http
    port: {{ .port }}
    targetPort: http
    {{- if .nodePort }}
    nodePort: {{ .nodePort | int }}
    {{- end }}
{{- end }}
